# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/enchilada/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),enchilada)

$(call add-radio-file-sha1-checked,radio/LOGO.img,eb2c7bb19991cd2e3b7330edc66e36bf9a3d94d1)
$(call add-radio-file-sha1-checked,radio/abl.img,e3ab0e222b0a136ea856627a315e2b1042a3e3e5)
$(call add-radio-file-sha1-checked,radio/aop.img,fece41bdd973efe622c1d4ec69c8739ec9203bde)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,29e5edb2a98df0d4775e8bbdd63703c66610cecb)
$(call add-radio-file-sha1-checked,radio/cmnlib.img,b7dea4e2a5b8037e512ab792069a2a013c658f6d)
$(call add-radio-file-sha1-checked,radio/cmnlib64.img,d1b34f5a2a8892c1b7053d2b62a7b328fcbc0495)
$(call add-radio-file-sha1-checked,radio/devcfg.img,4a4c4f0e52c39d515eeb34a854e7ff09c7672974)
$(call add-radio-file-sha1-checked,radio/dsp.img,9d5c3d72f6be752a8ea76dc3be1addbeab1273a0)
$(call add-radio-file-sha1-checked,radio/fw_4j1ed.img,a81acbfb24d1857a5e26a99b10f84e5d5029ba49)
$(call add-radio-file-sha1-checked,radio/fw_4u1ea.img,fe245ca416ff8617abafb95ff9112d97af0a59b6)
$(call add-radio-file-sha1-checked,radio/hyp.img,dc7cb9f75dbeaa2229951669b601259e1e4983fb)
$(call add-radio-file-sha1-checked,radio/keymaster.img,f967a6c5681c3e05387a3037c24d3b7eb39fcddc)
$(call add-radio-file-sha1-checked,radio/modem.img,abeb6d1f394e258acf50e167049498bdecb24cb6)
$(call add-radio-file-sha1-checked,radio/qupfw.img,f189239ed5baaeb849afeb7f22eb9744ffc9c68a)
$(call add-radio-file-sha1-checked,radio/storsec.img,244b430948b0c3eb23ea09d93aa8f6eda2e23d03)
$(call add-radio-file-sha1-checked,radio/tz.img,c13c912599d3f2c917eb2fd363395dd30e948139)
$(call add-radio-file-sha1-checked,radio/xbl.img,b85647360ecf2fe83086ef911861479c9ee39e84)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,716f318d497fbc5bdd68d1fdddbc4d9d7cd2c24b)

endif
